config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'todos#index'
  resources :todos
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
# frozen_string_literal: true

class Todo < ApplicationRecord
  mount_uploader :image, ::TodoUploader
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
# frozen_string_literal: true

class TodosController < ApplicationController
  def index
    @todos = Todo.all || Todo.none
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def new
    @todo = Todo.new
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def create
    @todo = Todo.create!(todo_params)
    redirect_to todo_path(@todo.id)
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update!(todo_params)
    redirect_to todo_path(@todo.id)
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy!
    redirect_to todos_path
  end

  private

  def todo_params
    params.require(:todo).permit(:title, :description, :image, :remove_image)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwsPracticeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/edit.html.erb
<%= form_with model: @todo do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.file_field :image %>
    <% if @todo.image? %>
      <%= image_tag(@todo.image.thumb.url) %>
      <%= f.label :remove_image %>
      <%= f.check_box :remove_image %>
    <% end %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/todos/index.html.erb
<div>
  <%= link_to '新規作成', new_todo_path %>
</div>

<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>作成日</th>
      <th>更新日</th>
      <th></th>
      <th></th>
  </thead>
  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= link_to todo.title, todo_path(todo.id) %></td>
        <td><%= todo.created_at %></td>
        <td><%= todo.updated_at %></td>
        <td><%= link_to '編集', edit_todo_path(todo.id) %></td>
        <td><%= button_to '削除', todo_path(todo.id), method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/todos/new.html.erb
<%= form_with model: @todo do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/todos/show.html.erb
<div>
  <%= link_to '一覧', todos_path %>
</div>

<table>
  <tr>
    <th>タイトル</th>
    <td><%= @todo.title %></td>
  </tr>
  <tr>
    <th>説明</th>
    <td><%= @todo.description %></td>
  </tr>
  <tr>
  <tr>
    <th>画像</th>
    <td>
      <% if @todo.image? %>
        <%= link_to(image_tag(@todo.image.thumb.url), @todo.image.url) %>
      <% else %>
        <%= image_tag(@todo.image.thumb.url) %>
      <% end %>
    </td>
  </tr>
  <tr>
    <th>作成日</th>
    <td><%= @todo.created_at %></td>
  </tr>
  <tr>
    <th>更新日</th>
    <td><%= @todo.updated_at %></td>
  </tr>
  <tr>
    <td><%= link_to '編集', edit_todo_path(@todo.id) %></td>
  </tr>
  <tr>
    <td><%= button_to '削除', todo_path(@todo.id), method: :delete %></td>
  </tr>
</table>